"""init

Revision ID: d96bf4bf3e4f
Revises: 
Create Date: 2020-06-24 03:12:18.119705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd96bf4bf3e4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.String(length=32), nullable=False),
    sa.Column('comment_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('from_anchor', sa.Boolean(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('reply_to_comment', sa.String(length=32), nullable=True),
    sa.Column('reply_to_user_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_nick', sa.Unicode(length=32), nullable=True),
    sa.Column('sns_nick', sa.Unicode(length=32), nullable=True),
    sa.Column('taoqihi', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=32), nullable=True),
    sa.Column('os', sa.String(length=32), nullable=True),
    sa.Column('fan_score', sa.Integer(), nullable=True),
    sa.Column('fan_level', sa.Integer(), nullable=True),
    sa.Column('vip_user', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('show_id', 'comment_id')
    )
    op.create_index('idx_show_comment', 'comment', ['show_id', 'comment_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_index(op.f('ix_comment_user_nick'), 'comment', ['user_nick'], unique=False)
    op.create_table('live_show',
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('seller_nick', sa.Unicode(length=32), nullable=False),
    sa.Column('title', sa.Unicode(length=128), nullable=True),
    sa.Column('favor_image', sa.String(length=256), nullable=True),
    sa.Column('cover_image', sa.String(length=256), nullable=True),
    sa.Column('landscape', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Unicode(length=32), nullable=True),
    sa.Column('approval', sa.Integer(), nullable=True),
    sa.Column('estimated_start_at', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.Integer(), nullable=True),
    sa.Column('end_at', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.Integer(), nullable=True),
    sa.Column('room_status', sa.Integer(), nullable=True),
    sa.Column('live_url', sa.String(length=512), nullable=True),
    sa.Column('live_channel_id', sa.Integer(), nullable=True),
    sa.Column('live_column_id', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('topic', sa.String(length=36), nullable=True),
    sa.Column('_type', sa.Integer(), nullable=True),
    sa.Column('has_data_permission', sa.Boolean(), nullable=True),
    sa.Column('share_to_mall', sa.String(length=32), nullable=True),
    sa.Column('use_lcps', sa.Boolean(), nullable=True),
    sa.Column('lcps_id', sa.Integer(), nullable=True),
    sa.Column('feed_detail', sa.String(length=512), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.String(length=32), nullable=True),
    sa.Column('video_status', sa.Integer(), nullable=True),
    sa.Column('video_play_url', sa.String(length=512), nullable=True),
    sa.Column('rate_adapt', sa.Boolean(), nullable=True),
    sa.Column('publish_source', sa.Integer(), nullable=True),
    sa.Column('is_h265', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.Text(length=16777215), nullable=True),
    sa.Column('extend', sa.Text(length=16777215), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_show_id'), 'live_show', ['id'], unique=False)
    op.create_index(op.f('ix_live_show_seller_id'), 'live_show', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_show_seller_id'), table_name='live_show')
    op.drop_index(op.f('ix_live_show_id'), table_name='live_show')
    op.drop_table('live_show')
    op.drop_index(op.f('ix_comment_user_nick'), table_name='comment')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index('idx_show_comment', table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
